language: generic
os:
- osx
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - libcurl
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
script:
- mkdir build
- cd build
- cmake .. && make
